language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - CONNECTION_STRING=:memory:
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest discover -s ./tests/
notifications:
  email:
    on_success: never
    on_failure: change

